Repository sp-19team/RetroQuest, pull requests merged in 2023-08, with the labels that each got.

#9 addPost UI 잔잔바리 수정[DESIGN] : 🎨
  app/src/main/java/com/example/retroquest/AddPostActivity.kt
  app/src/main/java/com/example/retroquest/ComunityActivity.kt
  app/src/main/res/drawable/cuvi2.png
  app/src/main/res/drawable/mario2.png
  app/src/main/res/drawable/picachu.png
  app/src/main/res/drawable/sonci3.png
  app/src/main/res/drawable/star.gif
  app/src/main/res/drawable/weather1.png
  app/src/main/res/drawable/weather2.png
  app/src/main/res/drawable/weather3.png
  app/src/main/res/drawable/weather4.png
  app/src/main/res/drawable/weather5.png
  app/src/main/res/drawable/weather6.png
  app/src/main/res/layout/activity_add_post.xml
  app/src/main/res/layout/activity_comunity.xml
Labels: bug

#20 [Fix] login/signUp.xml,[enhancement] sting.xml(en)
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, Fix

#21 [FEAT] : 퀘스트 버튼별 인텐트로 넘겨주는 데이터 작성
  app/src/main/java/com/example/retroquest/MainActivity.kt
  app/src/main/java/com/example/retroquest/QuestData.kt
  app/src/main/res/layout/activity_main.xml
Labels: Feat

#22 [FIX] : 🔧 퀘스트 내용 추가
  app/src/main/java/com/example/retroquest/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: Fix

#23 [FIX] userList string 수정, [FEAT] string xml 한글, 영어 파일 string 추가
  app/src/main/res/layout/activity_user_list.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, Fix

#26 [FEAT] : ⚙️ 게임액티비티 생성 같은그림찾기
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/retroquest/DetailUsersActivity.kt
  app/src/main/java/com/example/retroquest/GameActivity.kt
  app/src/main/java/com/example/retroquest/GameCard.kt
  app/src/main/res/drawable/esang.png
  app/src/main/res/drawable/esang2.png
  app/src/main/res/drawable/gamestart.png
  app/src/main/res/drawable/gobuk1.png
  app/src/main/res/drawable/gobuk2.png
  app/src/main/res/drawable/pairy.png
  app/src/main/res/drawable/pariy2.png
  app/src/main/res/drawable/poketball.png
  app/src/main/res/drawable/richu.png
  app/src/main/res/layout/activity_detail_users.xml
  app/src/main/res/layout/activity_game.xml
Labels: Feat

#27 [FEAT] login, signup 액티비티 이동 간 슬라이드 기능 추가 [DOCS] 주석 추가
  app/src/main/java/com/example/retroquest/LoginActivity.kt
  app/src/main/java/com/example/retroquest/SignUpActivity.kt
Labels: enhancement, Fix

#28 DetailQuest 수정작업 안내
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/retroquest/DetailQuestActivity.kt
  app/src/main/java/com/example/retroquest/QuestData.kt
  app/src/main/res/layout/activity_detail_quest.xml
Labels: Fix

#29 [Fix] string.xml(en)text내용 영어로 수정
  app/src/main/res/layout/activity_add_post.xml
  app/src/main/res/layout/activity_comunity.xml
  app/src/main/res/layout/activity_detail_users.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: Fix

#30 [FEAT] : ⚙️퀘스트버튼 기능추가
  app/src/main/java/com/example/retroquest/DetailQuestActivity.kt
  app/src/main/java/com/example/retroquest/MainActivity.kt
  app/src/main/res/layout/activity_detail_quest.xml
Labels: Feat

#31 [FIX] : 🔧 커뮤니티액티비티 아이템클릭시 토글효과줘서 게시물보이게 수정
  app/src/main/java/com/example/retroquest/ComunityActivity.kt
  app/src/main/java/com/example/retroquest/DetailUsersActivity.kt
  app/src/main/java/com/example/retroquest/PostData.kt
  app/src/main/res/layout/activity_detail_post.xml
  app/src/main/res/layout/activity_post_item.xml
Labels: Feat

#33 [FEAT] : ⚙ 퀘스트 보상 수령 액티비티
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/retroquest/DetailQuestActivity.kt
  app/src/main/java/com/example/retroquest/MainActivity.kt
  app/src/main/java/com/example/retroquest/ResultActivity.kt
  app/src/main/java/com/example/retroquest/ResultData.kt
  app/src/main/res/drawable/button2.png
  app/src/main/res/drawable/clear.png
  app/src/main/res/drawable/quest3.png
  app/src/main/res/drawable/questback.jpeg
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_result.xml
Labels: Feat

#34 [Fix] loginActivity editText 색상 변경
  app/src/main/res/layout/activity_login.xml
Labels: Fix

#35 [FEAT] : ⚙ 퀘스트 보상 수령 기능
  app/src/main/java/com/example/retroquest/MainActivity.kt
  app/src/main/java/com/example/retroquest/ResultActivity.kt
  app/src/main/java/com/example/retroquest/ResultData.kt
Labels: Feat

#36 [DESIGN] : 🎨 프로필 gif로 움직이는 이미지로 바꿈
  app/src/main/java/com/example/retroquest/AddPostActivity.kt
  app/src/main/java/com/example/retroquest/DetailUsersActivity.kt
  app/src/main/java/com/example/retroquest/GameActivity.kt
  app/src/main/java/com/example/retroquest/LoginActivity.kt
  app/src/main/res/drawable/avocado.gif
  app/src/main/res/drawable/movecat.gif
  app/src/main/res/layout/activity_game.xml
  app/src/main/res/layout/activity_login.xml
Labels: Fix, Feat

#40 [FIX] : 🔧 각 보상 수령 버튼 연결
  app/src/main/java/com/example/retroquest/LoginActivity.kt
Labels: Fix

#41 [FIX] : 🔧 메인 액티비티 수정
  app/src/main/java/com/example/retroquest/LoginActivity.kt
  app/src/main/java/com/example/retroquest/MainActivity.kt
Labels: Feat

#42 Feat2/detail quest
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/retroquest/DetailQuestActivity.kt
  app/src/main/res/layout/activity_detail_quest.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/ids.xml
Labels: Fix

#44 fix.⚙:메인엑티비티 오타수정 이미지뷰 1-5 수정
  app/src/main/java/com/example/retroquest/MainActivity.kt
Labels: bug

#45 dataclass 추가
  app/src/main/java/com/example/retroquest/DetailQuestActivity.kt
  app/src/main/java/com/example/retroquest/MainActivity.kt
  app/src/main/java/com/example/retroquest/QuestData.kt
Labels: Fix

#46 [MERGE] : ✅ main과 dev 최종 머지
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/retroquest/AddPostActivity.kt
  app/src/main/java/com/example/retroquest/ComunityActivity.kt
  app/src/main/java/com/example/retroquest/DetailQuestActivity.kt
  app/src/main/java/com/example/retroquest/DetailUsersActivity.kt
  app/src/main/java/com/example/retroquest/GameActivity.kt
  app/src/main/java/com/example/retroquest/GameCard.kt
  app/src/main/java/com/example/retroquest/LoginActivity.kt
  app/src/main/java/com/example/retroquest/MainActivity.kt
  app/src/main/java/com/example/retroquest/PostData.kt
  app/src/main/java/com/example/retroquest/QuestData.kt
  app/src/main/java/com/example/retroquest/ResultActivity.kt
  app/src/main/java/com/example/retroquest/ResultData.kt
  app/src/main/java/com/example/retroquest/SignUpActivity.kt
  app/src/main/java/com/example/retroquest/UserListActivity.kt
  app/src/main/res/drawable/avocado.gif
  app/src/main/res/drawable/backbtn.png
  app/src/main/res/drawable/black_label.png
  app/src/main/res/drawable/button2.png
  app/src/main/res/drawable/clear.png
  app/src/main/res/drawable/esang.png
  app/src/main/res/drawable/esang2.png
  app/src/main/res/drawable/gamestart.png
  app/src/main/res/drawable/gobuk1.png
  app/src/main/res/drawable/gobuk2.png
  app/src/main/res/drawable/movecat.gif
  app/src/main/res/drawable/pairy.png
  app/src/main/res/drawable/pariy2.png
  app/src/main/res/drawable/pic1.png
  app/src/main/res/drawable/pic2.png
  app/src/main/res/drawable/pic3.png
  app/src/main/res/drawable/pic4.png
  app/src/main/res/drawable/play1.png
  app/src/main/res/drawable/play2.png
  app/src/main/res/drawable/play3.png
  app/src/main/res/drawable/play4.png
  app/src/main/res/drawable/poketball.png
  app/src/main/res/drawable/postback.jpg
  app/src/main/res/drawable/quest3.png
  app/src/main/res/drawable/questback.jpg
  app/src/main/res/drawable/questbtn.png
  app/src/main/res/drawable/richu.png
  app/src/main/res/drawable/start1.png
  app/src/main/res/layout/activity_add_post.xml
  app/src/main/res/layout/activity_comunity.xml
  app/src/main/res/layout/activity_detail_quest.xml
  app/src/main/res/layout/activity_detail_users.xml
  app/src/main/res/layout/activity_game.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_post_item.xml
  app/src/main/res/layout/activity_result.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_user_list.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/ids.xml
  app/src/main/res/values/strings.xml
Labels: good first issue

#47 [FIX] : 🔧 아이콘 변경 기능
  app/src/main/java/com/example/retroquest/DetailQuestActivity.kt
Labels: Fix

#49 [MERGE] : ✅ 발표용 기능 추가 병합2
  README.md
  app/src/main/java/com/example/retroquest/DetailQuestActivity.kt
Labels: good first issue
